{
 "title": "Hello World",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Example Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 20, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "<img src=\"https://raw.githubusercontent.com/F5ObservabilityHub/AppFramework-Docs/refs/heads/main/docs/assets/example_developer_hello_world.png\" width=\"900px\" />"
     }
    }
   ]
  },
  { "title": "Example Visualizations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Hello-World Metric",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "targets": [
    { "expr": "metric_counter_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hello-World Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT Timestamp as \"timestamp\", Body as \"body\", SeverityText as \"level\", mapConcat(ResourceAttributes, LogAttributes) as \"labels\", TraceId as \"traceID\" FROM \"otel\".\"otel_logs\" WHERE ( timestamp >= $__fromTime AND timestamp <= $__toTime ) AND ResourceAttributes['service.name'] LIKE '%hello-world%' ORDER BY timestamp DESC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Hello-World Logs (Table)",
   "type": "table",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT Timestamp as \"timestamp\", Body as \"body\", SeverityText as \"level\", LogAttributes as \"logLabels\", ResourceAttributes as \"resourceLabels\", TraceId as \"traceID\" FROM \"otel\".\"otel_logs\" WHERE ( timestamp >= $__fromTime AND timestamp <= $__toTime ) AND ResourceAttributes['service.name'] LIKE '%hello-world%' ORDER BY timestamp DESC LIMIT 1000"
    }
   ]
  },
  {
   "title": "Hello-World Traces",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT \"TraceId\" as traceID, \"ServiceName\" as serviceName, \"SpanName\" as operationName, \"Timestamp\" as startTime, multiply(\"Duration\", 0.000001) as duration FROM \"otel\".\"otel_traces\" WHERE ( Timestamp >= $__fromTime AND Timestamp <= $__toTime ) AND ( ParentSpanId = '' ) AND ( Duration > 0 ) ORDER BY Timestamp DESC, Duration DESC LIMIT 1000"
    }
   ]
  }
 ]
}